('Alejandro', 'Iñárritu'),
  ('Damien', 'Chazelle'),
  ('Dan' , 'Gilroy'),
  ('James' , 'Gunn'),
  ('George' , 'Miller'),
  ('Alex' , 'Garland'),
  ('Denis' , 'Villeneuve'),
  ('Yorgos' , 'Lanthimos'),
  ('Stanley' , 'Kubrick'),
  ('Neill' , 'Blomkamp'),
  ('Francis' , 'Ford Coppola'),
  ('Woody' , 'Allen'),
  ('Paul Thomas' , 'Anderson'),
  ('Michael' , 'Powell'),
  ('Martin' , 'Scorsese'),
  ('Quentin' , 'Tarantino'),
  ('Joel' , 'Coen'),
  ('Roman' , 'Polanski'),
  ('Sam' , 'Mendes');
